SELECT CAST(E3TimeStamp AS DATE) [DATA], ROUND(SUM("EM-1Piranometro GHI" * 30 / 3600) / 1000,2) AS "IRRADIAÇÃO GHI (kWh/m²)"
FROM EM1
WHERE CAST(E3TimeStamp AS DATE) BETWEEN (SELECT DATEADD( DAY, 1, EOMONTH(GETDATE(), -2))) AND (SELECT EOMONTH( GETDATE(), -1))
GROUP BY CAST(E3TimeStamp AS DATE)
ORDER BY [DATA] ASC